version: "3.9"
services:
  robomaster_cv:
    extends:
      file: docker-compose-gui.yml
      service: robomaster_cv
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia