version: "3.9"
services:
  robomaster_cv:
    extends:
      file: docker-compose.yml
      service: robomaster_cv
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
