ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG LIBREALSENSE_SOURCE_VERSION=v2.55.1

COPY scripts/install-realsense-dependencies.sh /opt/realsense/install-realsense-dependencies.sh
RUN chmod +x /opt/realsense/install-realsense-dependencies.sh && \
    /opt/realsense/install-realsense-dependencies.sh;

COPY scripts/build-librealsense.sh /opt/realsense/build-librealsense.sh
RUN chmod +x /opt/realsense/build-librealsense.sh
RUN /opt/realsense/build-librealsense.sh -n -v ${LIBREALSENSE_SOURCE_VERSION};

# Copy hotplug script for udev rules/hotplug for RealSense
RUN mkdir -p /opt/realsense/
COPY scripts/hotplug-realsense.sh /opt/realsense/hotplug-realsense.sh
RUN chmod +x /opt/realsense/hotplug-realsense.sh
COPY udev_rules/99-realsense-libusb-custom.rules /etc/udev/rules.d/99-realsense-libusb-custom.rules
RUN sudo cp /root/librealsense/config/99-realsense-libusb.rules /etc/udev/rules.d/