ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install helpful tools
RUN apt-get update && apt-get install -y \
        vim \
        nano \
        dos2unix \
        ffmpeg \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean

RUN git clone https://github.com/mlaiacker/rosbag2video.git